name:  limesurvey
version: '2.62.0'
summary: Sophisticated online survey software
description: |
 LimeSurvey is the No.1 open-source survey software worldwide.
 For more information have a look at https://limesurvey.org, or find us on github/limesurvey

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  # Apache daemon
  apache:
    command: run-httpd -k start -DFOREGROUND
    stop-command: run-httpd -k stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  # MySQL daemon
  mysql:
    command: start_mysql
    stop-command: support-files/mysql.server stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  # PHP FPM daemon
  php-fpm:
    command: start-php-fpm
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, removable-media]
  # MySQL client
  mysql-client:
    command: mysql --defaults-file=$SNAP_DATA/mysql/root.ini
    plugs: [network, network-bind]

  mysqldump:
    command: mysqldump --defaults-file=$SNAP_DATA/mysql/root.ini --lock-tables limesurvey
    plugs: [network, network-bind]

  enable-https:
    command: enable-https
    plugs: [network, network-bind]

  disable-https:
    command: disable-https
    plugs: [network, network-bind]

  renew-certs:
    command: renew-certs
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

  limesurvey:
    command: setup_limesurvey

parts:
  apache:
    plugin: apache
    source: http://ftp.wayne.edu/apache/httpd/httpd-2.4.25.tar.bz2

    # The built-in Apache modules to enable
    modules:
      - headers
      - proxy
      - proxy_fcgi
      - setenvif
      - env
      - rewrite
      - mime
      - dir
      - authz_core
      - unixd
      - alias
      - ssl
      - socache_shmcb

    filesets:
      exclude:
        - -man
        - -manual
        - -htdocs
        - -include
        - -build
        - -conf/httpd.conf
        - -conf/magic
        - -conf/original
        - -conf/extra
        - -bin/apachectl
        - -bin/envvars*
    stage:
      - $exclude
    prime:
      - $exclude

  apache-customizations:
    plugin: dump
    after: [apache]
    source:
      ./src/apache/
    organize:
      scripts/: bin/
      conf/: conf/


  php:
    plugin: php
    source: http://us1.php.net/get/php-7.0.15.tar.bz2/from/this/mirror
    source-type: tar
    install-via: prefix
    configflags:
      - --enable-fpm
      - --disable-cgi
      - --disable-phar
      - --disable-phpdbg
      - --enable-ctype
      - --enable-mbstring
      - --enable-zip
      - --with-pdo-mysql
      - --with-zlib
      - --with-gd
      - --with-curl
      - --with-openssl
      - --with-bz2
      - --with-mcrypt
      - --enable-exif
      - --enable-intl
      - --with-jpeg-dir=/usr/lib
      - --disable-rpath
    stage-packages:
      # These are only included here until the OS snap stabilizes
      - libxml2
      - libpng12-0
    build-packages:
      - libxml2-dev
      - libcurl4-openssl-dev
      - libpng12-dev
      - libjpeg9-dev
      - libbz2-dev
      - libmcrypt-dev
    prime:
     - -sbin/
     - -etc/
    organize:
      # Put php-fpm in bin with everything else, not sbin.
      sbin/php-fpm: bin/php-fpm
    extensions:
      # Build the redis PHP module
      - source: https://github.com/phpredis/phpredis.git
        source-branch: php7

  # Copy over our PHP configuration file.
  php-customizations:
    plugin: dump
    source:
      ./src/php/
    organize:
      config/: config/php/
      scripts/: bin/
    stage-packages: [mawk]

  # Download the boost headers for MySQL. Note that the version used may need to
  # be updated if the version of MySQL changes.
  boost:
    plugin: dump
    source: ./src/boost/boost_1_59_0.tar.gz
    organize:
      '*': $SNAPCRAFT_STAGE/boost/
    prime:
      - '*'

  mysql:
    plugin: cmake
    source: https://github.com/kyrofa/mysql-server.git
    source-type: git
    source-branch: feature/support_no_setpriority
    after: [boost]
    configflags:
      - -DWITH_BOOST=$SNAPCRAFT_STAGE/boost
      - -DDOWNLOAD_BOOST=1
      - -DWITH_INNODB_PAGE_CLEANER_PRIORITY=OFF
      - -DCMAKE_INSTALL_PREFIX=/
      - -DBUILD_CONFIG=mysql_release
      - -DWITH_UNIT_TESTS=OFF
      - -DWITH_EMBEDDED_SERVER=OFF
      - -DWITH_EMBEDDED_SHARED_LIBRARY=OFF
      - -DWITH_ARCHIVE_STORAGE_ENGINE=OFF
      - -DWITH_BLACKHOLE_STORAGE_ENGINE=OFF
      - -DWITH_FEDERATED_STORAGE_ENGINE=OFF
      - -DWITH_PARTITION_STORAGE_ENGINE=OFF
      - -DINSTALL_MYSQLTESTDIR=
    build-packages:
      - wget
      - g++
      - cmake
      - bison
      - libncurses5-dev
      - libaio-dev
    stage:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server
    prime:
      # Remove unused binaries that waste space
      - -bin/innochecksum
      - -bin/lz4_decompress
      - -bin/mysqladmin
      - -bin/mysqlbinlog
      - -bin/mysql_client_test
      - -bin/mysql_config*
      - -bin/mysqld_multi
      - -bin/mysqlimport
      - -bin/mysql_install_db
      - -bin/mysql_plugin
      - -bin/mysqlpump
      - -bin/mysql_secure_installation
      - -bin/mysqlshow
      - -bin/mysqlslap
      - -bin/mysql_ssl_rsa_setup
      - -bin/mysqltest
      - -bin/mysql_tzinfo_to_sql
      - -bin/perror
      - -bin/replace
      - -bin/resolveip
      - -bin/resolve_stack_dump
      - -bin/zlib_decompress

  # Copy over our MySQL scripts
  mysql-customizations:
    plugin: dump
    source:
      ./src/mysql/
    organize:
      start_mysql: bin/start_mysql
      my.cnf: support-files/my.cnf
      mysql.server: support-files/mysql.server

  delay-on-failure:
    plugin: dump
    source:
      ./src/delay-on-failure/
    organize:
      delay-on-failure: bin/delay-on-failure

  setup-https:
    plugin: dump
    source:
      ./src/https/
    organize:
      scripts/: usr/bin/
      utilities/: utilities/
    stage-packages: [openssl]
    stage: [ '-etc/ssl', '-src/https/' ]
    prime: [ '-etc/ssl', '-src/https/' ]

  limesurvey:
    plugin: dump
    source-type: 'git'
    source-tag: '2.62.0+170124'
    source: https://github.com/LimeSurvey/LimeSurvey
    organize:
      '*': htdocs/

  limesurvey-extra:
    plugin: dump
    after: [ mysql, php, apache, limesurvey ]
    source:
      './src/limesurvey/'
    organize:
      scripts/: bin/
      config/: htdocs/application/config
